//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace IndicativeExchangeRates.Model.Schemas.XML
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Tarih_Date {
        
        private Tarih_DateCurrency[] currencyField;
        
        private string tarihField;
        
        private string dateField;
        
        private string bulten_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Currency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Tarih_DateCurrency[] Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Bulten_No {
            get {
                return this.bulten_NoField;
            }
            set {
                this.bulten_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class Tarih_DateCurrency {
        
        private byte unitField;
        
        private bool unitFieldSpecified;
        
        private string isimField;
        
        private string currencyNameField;
        
        private decimal forexBuyingField;
        
        private bool forexBuyingFieldSpecified;
        
        private decimal forexSellingField;
        
        private bool forexSellingFieldSpecified;
        
        private decimal banknoteBuyingField;
        
        private bool banknoteBuyingFieldSpecified;
        
        private decimal banknoteSellingField;
        
        private bool banknoteSellingFieldSpecified;
        
        private decimal crossRateUSDField;
        
        private bool crossRateUSDFieldSpecified;
        
        private decimal crossRateOtherField;
        
        private bool crossRateOtherFieldSpecified;
        
        private byte crossOrderField;
        
        private bool crossOrderFieldSpecified;
        
        private string kodField;
        
        private string currencyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitSpecified {
            get {
                return this.unitFieldSpecified;
            }
            set {
                this.unitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Isim {
            get {
                return this.isimField;
            }
            set {
                this.isimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyName {
            get {
                return this.currencyNameField;
            }
            set {
                this.currencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ForexBuying {
            get {
                return this.forexBuyingField;
            }
            set {
                this.forexBuyingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForexBuyingSpecified {
            get {
                return this.forexBuyingFieldSpecified;
            }
            set {
                this.forexBuyingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ForexSelling {
            get {
                return this.forexSellingField;
            }
            set {
                this.forexSellingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForexSellingSpecified {
            get {
                return this.forexSellingFieldSpecified;
            }
            set {
                this.forexSellingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BanknoteBuying {
            get {
                return this.banknoteBuyingField;
            }
            set {
                this.banknoteBuyingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BanknoteBuyingSpecified {
            get {
                return this.banknoteBuyingFieldSpecified;
            }
            set {
                this.banknoteBuyingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BanknoteSelling {
            get {
                return this.banknoteSellingField;
            }
            set {
                this.banknoteSellingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BanknoteSellingSpecified {
            get {
                return this.banknoteSellingFieldSpecified;
            }
            set {
                this.banknoteSellingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CrossRateUSD {
            get {
                return this.crossRateUSDField;
            }
            set {
                this.crossRateUSDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CrossRateUSDSpecified {
            get {
                return this.crossRateUSDFieldSpecified;
            }
            set {
                this.crossRateUSDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CrossRateOther {
            get {
                return this.crossRateOtherField;
            }
            set {
                this.crossRateOtherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CrossRateOtherSpecified {
            get {
                return this.crossRateOtherFieldSpecified;
            }
            set {
                this.crossRateOtherFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte CrossOrder {
            get {
                return this.crossOrderField;
            }
            set {
                this.crossOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CrossOrderSpecified {
            get {
                return this.crossOrderFieldSpecified;
            }
            set {
                this.crossOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CurrencyXML {
        
        private Tarih_Date[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tarih_Date")]
        public Tarih_Date[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
